#!/bin/bash
#
# These are the service accounts we will use to start the docker containers
# The service accounts are primarily served to store the persistent configuration and avoid starting containers as root users
# In the container we should also define the service users with the save UID we are using on the host
# best practice is to build the container using the UID and name of the host service account (--user and --uid parameters) 
#

SERVICE_USER="service";
SERVICE_USER_UID="9001";
SERVICE_GROUP="services";
SERVICE_GROUP_UID="9001";
ADD_GROUPS="sudo"

#
# Create service group and service account
#
userdel $SERVICE_USER >/dev/null 2>&1;
groupdel $SERVICE_GROUP >/dev/null 2>&1;

groupadd -g $SERVICE_GROUP_UID $SERVICE_GROUP;
useradd -u $SERVICE_USER_UID -g $SERVICE_GROUP --groups $ADD_GROUPS --shell /bin/bash --create-home $SERVICE_USER;
chown -R $SERVICE_USER:$SERVICE_GROUP /home/$SERVICE_USER/;

#
# Allow service account to sudo without pasword
#
if [ ! -f /etc/sudoers.d/090_"$SERVICE_USER"-nopasswd ]; then
    echo "${SERVICEUSER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/090_"$SERVICE_USER"-nopasswd;
fi

#
# Create persistent config directory, will be exposed as volume to the docker container
#
if [ ! -d "/var/lib/services/deconz" ]; then
    mkdir -p /var/lib/services/deconz/;
fi
if [ ! -d "/var/lib/services/node-red" ]; then
    mkdir -p /var/lib/services/node-red/;
fi
if [ ! -d "/var/lib/services/openhab" ]; then
    mkdir -p /var/lib/services/openhab/;
fi
#
# Ensure access from host to the container directories
# Giving access to the local service user and the root, just in case the UID of the container service user differs from the host UID 
#
chown -R "$SERVICE_USER":root /var/lib/services/deconz/;
chown -R "$SERVICE_USER":root /var/lib/services/node-red/;
chown -R "$SERVICE_USER":root /var/lib/services/openhab/;


# ln /home/"${SERVICE_USER}"/deconz/systemd/deconz-docker@.service /etc/systemd/system/deconz-docker@.service
# systemctl enable deconz-docker@"${SERVICE_USER}"
# systemctl start deconz-docker@"${SERVICE_USER}"

# ln /home/"${SERVICE_USER}"/node-red/systemd/nodered-docker@.service /etc/systemd/system/nodered-docker@.service
# systemctl enable nodered-docker@"${SERVICE_USER}"


# systemctl start deconz-docker@"${SERVICE_USER}"

